Implement ALU
FPGACPU/CPU pull request #1
Opened 2022-12-29 13:08 UTC by JuanLuqueGaze

2022-12-29 13:12 UTC, aleokdev requested changes

2022-12-29 13:12 UTC, aleokdev commented on CPU.srcs/sim_1/new/alu_tb.vhd
> +----------------------------------------------------------------------------------
This is bloat -- get rid of it

2022-12-29 13:12 UTC, aleokdev commented on CPU.srcs/sim_1/new/alu_tb.vhd
> +--use UNISIM.VComponents.all;
These comments are not very useful

2022-12-29 13:12 UTC, aleokdev commented on CPU.srcs/sim_1/new/alu_tb.vhd
> +    --  Port ( );
Get rid of this comment as well

2022-12-29 13:12 UTC, aleokdev commented on CPU.srcs/sources_1/new/alu.vhd
> +----------------------------------------------------------------------------------
Get rid of these as well

2022-12-29 13:12 UTC, aleokdev commented on CPU.srcs/sources_1/new/alu.vhd
> +--use UNISIM.VComponents.all;
Same here

2022-12-29 13:12 UTC, aleokdev commented on CPU.srcs/sources_1/new/alu.vhd
> +    --  Port ( );
This

2022-12-29 13:13 UTC, Shuff-Alv commented on CPU.srcs/sim_1/new/alu_tb.vhd
> +            pac, tra2, dec, sum : IN STD_LOGIC;
qeu locura

2022-12-29 13:13 UTC, Shuff-Alv commented on CPU.srcs/sources_1/new/alu.vhd
> +----------------------------------------------------------------------------------
im on it

2022-12-29 14:21 UTC, aleokdev commented on CPU.srcs/sources_1/new/alu.vhd
> +    z <= '1' WHEN (presult = "000000000")
```vhdl
with presult select
  z <= '1' when (others => '0'),
     '0' when others;
```
Might be valid here?

2022-12-30 09:55 UTC, aleokdev commented on CPU.xpr
> +<Project Version="7" Minor="61" Path="C:/Users/Juan Luque/Documents/FPGA/CPU/CPU.xpr">
Deberiamos ver como no subir esta info...

2022-12-30 09:55 UTC, aleokdev approved these changes

2022-12-30 10:31 UTC, marcasmar1 commented on CPU.srcs/sources_1/new/alu.vhd
> +            WHEN "1000" => presult(0 TO (N - 1)) <= (OTHERS => '0');
```suggestion
            WHEN "1000" => presult(0 TO (N - 1)) <= (OTHERS => '0');    --pac
```

2022-12-30 10:35 UTC, marcasmar1 commented on CPU.srcs/sources_1/new/alu.vhd
> +            WHEN "0001" => presult <= data1 + data2;
Ale pon esto más bonito pero sabes la idea general
```suggestion
            WHEN "1000" => presult(0 TO (N - 1)) <= (OTHERS => '0');   --pac
            WHEN "0100" => presult <= data2;                           --tra2
            WHEN "0010" => presult <= data1 - 1;                       --dec
            WHEN "0001" => presult <= data1 + data2;                   --sum
```

2022-12-30 10:37 UTC, marcasmar1 commented on CPU.srcs/sources_1/new/alu.vhd
> +    SIGNAL presult : unsigned(0 TO (N - 1));
no me convence llamar a la señal presult

2022-12-30 10:38 UTC, marcasmar1 commented on CPU.srcs/sim_1/new/alu_tb.vhd
> +            data1 : IN unsigned(0 TO 8);
Esto hay que cambiarlo????? (con lod generic y eso)

2022-12-30 11:15 UTC, aleokdev commented on CPU.srcs/sim_1/new/alu_tb.vhd
> +            data1 : IN unsigned(0 TO 8);
Tecnicamente si

2022-12-30 11:53 UTC, marcasmar1 approved these changes

2022-12-30 11:54 UTC, merged