Implement sequencer
FPGACPU/CPU pull request #3
Opened 2022-12-30 15:09 UTC by aleokdev

2022-12-31 04:06 UTC, Shuff-Alv reviewed
please read all the commentaries

2022-12-31 04:06 UTC, Shuff-Alv commented on CPU.srcs/sources_1/new/sequencer.vhd
> +LIBRARY IEEE;
i really want to finish the sequencer but its too late at night and there are still so many errors.

Tell me what do you think about the code below and the improvements that i can do tomorrow pls.

2022-12-31 08:43 UTC, aleokdev commented on CPU.srcs/sources_1/new/sequencer.vhd
> +    -------------------------------------------------------change
I see what you're trying to do here, but I don't think it's really needed.
The reason you cannot change the outputs directly is most likely because outputs need to be combinatorial, but modifying in the way you are doing here is creating a register.

What you could do instead is create registers for each one of the microinstructions, modify those instead and then connect them over to the outputs, but I believe that even that is not required, as you can obtain the microsignals required depending on the current state of the sequencer (I0/I1/O0/O1) + the operation being done (CO) + the Z bit.

2022-12-31 08:45 UTC, aleokdev commented on CPU.srcs/sources_1/new/sequencer.vhd
> +        ----------------------------------------------change
No, it's just that `when` requires an `else` branch as well, which you haven't included. If you want to keep the previous value of the register I believe you can do something like
```vhdl
reg <= ... when (...) else UNAFFECTED;
```

2022-12-31 14:26 UTC, Shuff-Alv commented on CPU.srcs/sources_1/new/sequencer.vhd
> +        ----------------------------------------------change
the problem is that vivado says: "ERROR: this construct is only supported in VHDL 1076-2008"

2022-12-31 15:52 UTC, aleokdev commented on CPU.srcs/sources_1/new/sequencer.vhd
> +        ----------------------------------------------change
Might be because you're trying to use `when` inside a process; Try using an if instead.

2022-12-31 17:32 UTC, Shuff-Alv commented on CPU.srcs/sources_1/new/sequencer.vhd
> +        ----------------------------------------------change
That made the trick, thx

2023-01-01 14:18 UTC, aleokdev commented on CPU.srcs/sources_1/new/sequencer.vhd
> +    sequencer : PROCESS (CLK, lec, esc, pac, tra2, dec, sum, eac, sac, scp, ecp, incp, ccp, era, sri, eri, z, CO)
AFAIK only signals that are read need to be in the sensibility list.

2023-01-01 14:18 UTC, aleokdev commented on CPU.srcs/sources_1/new/sequencer.vhd
> +    SIGNAL I0, I1, O0, O1 : STD_LOGIC;
This can be simplified using a single unsigned that counts up on each cycle. Then you can identify 00 = I0, 01 = I1, 10 = O0, 11 = O1

2023-01-01 14:20 UTC, Shuff-Alv commented on CPU.srcs/sources_1/new/sequencer.vhd
> +    sequencer : PROCESS (CLK, lec, esc, pac, tra2, dec, sum, eac, sac, scp, ecp, incp, ccp, era, sri, eri, z, CO)
ouuu that saves me, thxx

2023-01-01 16:26 UTC, aleokdev commented on CPU.srcs/sources_1/new/sequencer.vhd
> +            IF (CO = "000") THEN --ST
You can use a case for all of this; It'll be shorter and more readable.

2023-01-01 16:51 UTC, Shuff-Alv commented on CPU.srcs/sources_1/new/sequencer.vhd
> +            IF (CO = "000") THEN --ST
okay, I can do it

2023-01-04 09:26 UTC, marcasmar1 commented on CPU.srcs/sources_1/new/sequencer.vhd
> +            -- All the outputs should be initialized and restarted
Is this necessary?

2023-01-04 09:39 UTC, marcasmar1 reviewed
I've copied this from a comment in case you're wondering.

2023-01-04 09:39 UTC, marcasmar1 commented on CPU.srcs/sources_1/new/sequencer.vhd
> +            STATE <= "01";
I believe this approach with states (changing the states in the same process they are used) does work but I fundamentally disagree with it. The sequencer is a FSM (Finite State Machine or "Máquina de estado" lel) so I believe it would be better if we took that approach as in synchronous process - combinational process.
There are also a series of problems with the current solution (or at least I think they should be problems):
-No reset (halt doesnt do shit, though reset should be independent of halt)
-Outputs seem like they will create latches (no case others anywhere)
-Currently, the sequencer can't jump from I1 to I0 (for example), which isn't good (even if we add pipeline later on).
-idk, there probably are more things to rant about

2023-01-04 09:40 UTC, marcasmar1 requested changes
I've copied this from a comment in case you're wondering.
I believe this approach with states (changing the states in the same process they are used) does work but I fundamentally disagree with it. The sequencer is a FSM (Finite State Machine or "Máquina de estado" lel) so I believe it would be better if we took that approach as in synchronous process - combinational process.
There are also a series of problems with the current solution (or at least I think they should be problems):
-No reset (halt doesnt do shit, though reset should be independent of halt)
-Outputs seem like they will create latches (no case others anywhere)
-Currently, the sequencer can't jump from I1 to I0 (for example), which isn't good (even if we add pipeline later on).
-idk, there probably are more things to rant about

2023-01-04 09:41 UTC, marcasmar1 requested changes
I've copied this from a comment in case you're wondering.
I believe this approach with states (changing the states in the same process they are used) does work but I fundamentally disagree with it. The sequencer is a FSM (Finite State Machine or "Máquina de estado" lel) so I believe it would be better if we took that approach as in synchronous process - combinational process.
There are also a series of problems with the current solution (or at least I think they should be problems):
-No reset (halt doesnt do shit, though reset should be independent of halt)
-Outputs seem like they will create latches (no case others anywhere)
-Currently, the sequencer can't jump from I1 to I0 (for example), which isn't good (even if we add pipeline later on).
-idk, there probably are more things to rant about

2023-01-04 09:49 UTC, marcasmar1 commented on CPU.srcs/sources_1/new/sequencer.vhd
> +        IF (falling_edge(CLK) AND STATE = "11") THEN
love that you put a hint

2023-01-04 09:51 UTC, marcasmar1 commented on CPU.srcs/sources_1/new/sequencer.vhd
> +        IF (falling_edge(CLK) AND STATE = "11") THEN
I agree with this

2023-01-04 16:07 UTC, Shuff-Alv commented on CPU.srcs/sources_1/new/sequencer.vhd
> +            STATE <= "01";
I know I1 cant jump to I0 but I did it on porpose. I though that the sequencer worked this way. However I can change it if you want. I think its not hard

2023-01-04 16:07 UTC, Shuff-Alv commented on CPU.srcs/sources_1/new/sequencer.vhd
> +            -- All the outputs should be initialized and restarted
what do you mean? The falling edge?

2023-01-04 16:13 UTC, marcasmar1 commented on CPU.srcs/sources_1/new/sequencer.vhd
> +            -- All the outputs should be initialized and restarted
"-- All the outputs should be initialized and restarted "

2023-01-04 16:15 UTC, marcasmar1 commented on CPU.srcs/sources_1/new/sequencer.vhd
> +            STATE <= "01";
The main issue is that you have to rewrite/restructure the sequencer entirely

2023-01-10 10:39 UTC, marcasmar1 approved these changes

2023-01-12 09:30 UTC, merged