Created clk_module
FPGACPU/CPU pull request #8
Opened 2023-01-10 10:55 UTC by marcasmar1

2023-01-10 13:54 UTC, aleokdev requested changes

2023-01-10 13:54 UTC, aleokdev commented on CPU.srcs/sim_1/new/clk_module_tb.vhd
> +    SIGNAL clk_in, clk_out : STD_LOGIC := '0';
This is also setting the clk_out signal to 0, which is incorrect as the value is already set by the module.

2023-01-10 13:54 UTC, aleokdev commented on CPU.srcs/sources_1/new/clk_module.vhd
> +    GENERIC (N : INTEGER := 4); --Divider 2^(N-1)
Use a better name instead of N.

2023-01-10 13:54 UTC, aleokdev commented on CPU.srcs/sources_1/new/clk_module.vhd
> +            count <= new_count;
new_count is not required. Use count + 1.

2023-01-10 13:54 UTC, aleokdev commented on CPU.srcs/sources_1/new/clk_module.vhd
> +    clk_out <= STD_LOGIC(count(0));
This is not dividing anything. It should be N-1 instead of 0.

2023-01-10 14:03 UTC, marcasmar1 commented on CPU.srcs/sim_1/new/clk_module_tb.vhd
> +    SIGNAL clk_in, clk_out : STD_LOGIC := '0';
Its just initial value and its the test bench but I will fix it later.

2023-01-10 14:04 UTC, marcasmar1 commented on CPU.srcs/sources_1/new/clk_module.vhd
> +    GENERIC (N : INTEGER := 4); --Divider 2^(N-1)
Completely agree, I was thinking something along the lines of _divider_.

2023-01-10 14:06 UTC, marcasmar1 commented on CPU.srcs/sources_1/new/clk_module.vhd
> +    clk_out <= STD_LOGIC(count(0));
Ok so this where the botch begins: I thought the same until I performed the simulation. For **some reason** it works if I put count(0) in stead of coun(N-1). Then again, ***botch***.

2023-01-10 14:22 UTC, marcasmar1 commented on CPU.srcs/sources_1/new/clk_module.vhd
> +    clk_out <= STD_LOGIC(count(0));
I've been thinking about this and I have a theory: VHDL always takes the leftmost bit as most significant. By how we've usually been defining unsigneds, (0 to N-1) our most significant bit would actually be the bit 0. If this is true, then a potencial use is storing words in memory (big-endian vs little-endian).

2023-01-10 14:25 UTC, marcasmar1 commented on CPU.srcs/sources_1/new/clk_module.vhd
> +            count <= new_count;
true

2023-01-10 17:55 UTC, aleokdev requested changes

2023-01-10 17:55 UTC, aleokdev commented on CPU.srcs/sim_1/new/clk_module_tb.vhd
> +            trace : IN STD_LOGIC; --Synchronous activation
This should not be part of the divider, and instead be part of a parent clock module.

2023-01-10 17:57 UTC, marcasmar1 commented on CPU.srcs/sim_1/new/clk_module_tb.vhd
> +            trace : IN STD_LOGIC; --Synchronous activation
Yeah, so the clock divider is now the clock module.

2023-01-10 17:58 UTC, marcasmar1 commented on CPU.srcs/sim_1/new/clk_module_tb.vhd
> +            trace : IN STD_LOGIC; --Synchronous activation
In that I've completely rewritten the code of the divider so it technically only exists in previous builds.

2023-01-10 18:06 UTC, aleokdev commented on CPU.srcs/sources_1/new/clk_module.vhd
> +    clk_out <= STD_LOGIC(count(0));
Endianness doesn't have anything to do with bit order, it's about byte order, which I can't see to/downto helping with.

> VHDL always takes the leftmost bit as most significant

I believe it should be backwards? Otherwise it'd be `x DOWNTO y`.

2023-01-10 18:07 UTC, aleokdev commented on CPU.srcs/sim_1/new/clk_module_tb.vhd
> +            trace : IN STD_LOGIC; --Synchronous activation
> I've completely rewritten the code of the divider so it technically only exists in previous builds.

Can you clarify? We should have the divider be separate from the actual clock module so we can test it separately.

2023-01-10 18:07 UTC, aleokdev commented on CPU.srcs/sources_1/new/clk_module.vhd
> +    GENERIC (N : INTEGER := 4); --Divider 2^(N-1)
Perhaps `DIVISION` would be better in that case.

2023-01-10 18:20 UTC, marcasmar1 commented on CPU.srcs/sim_1/new/clk_module_tb.vhd
> +            trace : IN STD_LOGIC; --Synchronous activation
Why? I believe having it as a separate module won't make things easier to code/understand nor will it be useful later on. The current test bench works with the entire module and I don't think we need  to test the divider separately (the test is just a bit longer).

2023-01-10 18:20 UTC, marcasmar1 commented on CPU.srcs/sources_1/new/clk_module.vhd
> +    GENERIC (N : INTEGER := 4); --Divider 2^(N-1)
On it.

2023-01-10 18:21 UTC, aleokdev commented on CPU.srcs/sim_1/new/clk_module_tb.vhd
> +            trace : IN STD_LOGIC; --Synchronous activation
Okay, in that case I think it would be wise to rename the file to clk_module instead of clk_divider, as it does more things than just dividing the internal clock.

2023-01-10 18:25 UTC, marcasmar1 commented on CPU.srcs/sources_1/new/clk_module.vhd
> +    clk_out <= STD_LOGIC(count(0));
>Endianness doesn't have anything to do with bit order, it's about byte order, which I can't see to/downto helping with.

I forgot that, ups.
>I believe it should be backwards? Otherwise it'd be x DOWNTO y.

What I know is that at least from the test I performed count(0) was the most significant bit (count defined as **(0 to divider-1)**).

2023-01-10 18:25 UTC, marcasmar1 commented on CPU.srcs/sources_1/new/clk_module.vhd
> +    GENERIC (N : INTEGER := 4); --Divider 2^(N-1)
On second thought I'll do it later.

2023-01-10 18:40 UTC, marcasmar1 commented on CPU.srcs/sim_1/new/clk_module_tb.vhd
> +            trace : IN STD_LOGIC; --Synchronous activation
The odd thing is that the file named clock_divider is something in binary. It's probably trash but I'm not sure.

2023-01-10 18:58 UTC, aleokdev commented on CPU.srcs/sim_1/new/clk_module_tb.vhd
> +            trace : IN STD_LOGIC; --Synchronous activation
Oh right, the file is renamed. The entity is not though.

2023-01-10 21:14 UTC, marcasmar1 commented on CPU.srcs/sim_1/new/clk_module_tb.vhd
> +            trace : IN STD_LOGIC; --Synchronous activation
Umm actually I never named it divider. I'll fix the other issue.

2023-01-10 21:20 UTC, marcasmar1 commented on CPU.srcs/sources_1/new/clk_module.vhd
> +    GENERIC (N : INTEGER := 4); --Divider 2^(N-1)
Done

2023-01-11 10:41 UTC, aleokdev commented
The dcp file seems to be synthesis data so I'm pretty sure we can safely remove it from the repo.

2023-01-23 13:03 UTC, JuanLuqueGaze approved these changes

2023-01-23 13:13 UTC, Shuff-Alv approved these changes

2023-02-02 15:38 UTC, merged